from aiogram.types import KeyboardButton,ReplyKeyboardMarkup

cityuz= ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text="Toshkent")
        ],
        [
            KeyboardButton(text="Farg'ona"),
            KeyboardButton(text="Samarqand"),
        ],
        [
            KeyboardButton(text="Andijon"),
            KeyboardButton(text="Buxoro")
        ],
        [
            KeyboardButton(text="Guliston"),
            KeyboardButton(text="Jizzax"),
        ],
        [
            KeyboardButton(text="Zarafshon"),
            KeyboardButton(text="Qarshi"),
        ],
        [
            KeyboardButton(text="Navoiy"),
            KeyboardButton(text="Namangan"),
        ],
        [
            KeyboardButton(text="Nukus"),
            KeyboardButton(text="Termiz"),
        ],
        [
            KeyboardButton(text="Urganch"),
            KeyboardButton(text="Xiva")
        ],
        [
            KeyboardButton(text="🔙 Orqaga")
        ]
    ],resize_keyboard=True
)

cityru= ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text="Ташкент")
        ],
        [
            KeyboardButton(text="Фергана"),
            KeyboardButton(text="Самарканд"),
        ],
        [
            KeyboardButton(text="Андижан"),
            KeyboardButton(text="Бухара")
        ],
        [
            KeyboardButton(text="Гулистан"),
            KeyboardButton(text="Джизак"),
        ],
        [
            KeyboardButton(text="Зарафшон"),
            KeyboardButton(text="Қарши"),
        ],
        [
            KeyboardButton(text="Навои"),
            KeyboardButton(text="Наманган"),
        ],
        [
            KeyboardButton(text="Нукус"),
            KeyboardButton(text="Термиз"),
        ],
        [
            KeyboardButton(text="Ургенч"),
            KeyboardButton(text="Хива")
        ],
        [
            KeyboardButton(text="🔙 Назад")
        ]
    ],resize_keyboard=True
)